Attribute decoder
rkvst/rkvst-receipt-scitt pull request #2
Opened 2023-02-28 11:08 UTC by honourfish

Rkvst attribute decoder

2023-02-28 11:18 UTC, robinbryce commented on rkvst_receipt_scitt/attribute_decoder.py
> +
the contracts revert if the kind is not exactly one of the expected kinds. and they are all lower case. it would be fine to raise a ValueError or a TypeError rather than case smash. And possibly not doing so opens up subtle opportunities for faking receipt content. Cetainly though, the proof would not verify if the content here didn't match the rules enforced by our contracts

2023-02-28 11:26 UTC, Serhiy1 commented on rkvst_receipt_scitt/attribute_decoder.py
> +    Tuple,
We can use https://peps.python.org/pep-0563/ by importing `annotations` from the `__future__` module. 

This should allow us to use the nicer type syntax  ` -> Union[str, list, dict]` becomes `-> str | list | dict` 

And allow more accurate type hinting eg ` -> str | list[str] | dict[str,str]`

And allows us to use the base types as well `-> Tuple[AttributeType, str]` becomes `-> tuple[AttributeType, str]`

We use this in the python SDK and haven't had any issue with it

2023-02-28 11:28 UTC, honourfish commented on rkvst_receipt_scitt/attribute_decoder.py
> +    Tuple,
that looks much nicer! will change :)

2023-02-28 11:44 UTC, eccles requested changes
It would be nice if the code was automatically formatted with 'block'.

Some of the files have no newline at end of file which github is marking with a Red Blob -

2023-02-28 11:44 UTC, eccles commented on rkvst_receipt_scitt/attribute_decoder.py
> +        return value
put the 'return value' in an else clause - its best to minimise code in the try block

2023-02-28 11:44 UTC, eccles commented on rkvst_receipt_scitt/attribute_decoder.py
> +    else:
else is not needed

2023-02-28 11:44 UTC, eccles commented on rkvst_receipt_scitt/attribute_decoder.py
> +    dict_value = dict()
minor: use [] instead of list(), {} instead of dict()

2023-02-28 11:44 UTC, eccles commented on rkvst_receipt_scitt/verify_proof.py
> +#!/usr/bin/env python3
this line is not needed

2023-02-28 12:48 UTC, honourfish commented on rkvst_receipt_scitt/attribute_decoder.py
> +        return value
i think i would prefer to short circuit here, if we know its a string value lets just return the string value? instead of trying to decode a list or dict that we know is a string

2023-02-28 12:48 UTC, honourfish commented on rkvst_receipt_scitt/attribute_decoder.py
> +    else:
will remove

2023-02-28 12:48 UTC, honourfish commented on rkvst_receipt_scitt/attribute_decoder.py
> +    dict_value = dict()
will do :)

2023-02-28 12:49 UTC, honourfish commented on rkvst_receipt_scitt/verify_proof.py
> +#!/usr/bin/env python3
will remove

2023-02-28 12:59 UTC, honourfish commented on rkvst_receipt_scitt/verify_proof.py
> +#!/usr/bin/env python3
removed!

2023-02-28 13:00 UTC, honourfish commented on rkvst_receipt_scitt/attribute_decoder.py
> +    else:
done

2023-02-28 14:32 UTC, honourfish commented on rkvst_receipt_scitt/attribute_decoder.py
> +    Tuple,
done!

2023-02-28 14:34 UTC, honourfish commented on rkvst_receipt_scitt/attribute_decoder.py
> +
I think i would prefer to be explicit, it makes it easier to reconstruct the event api response, or at least in a comparable way. 

It is hopefully also more obvious what the values are we allow, which gives a customer a better inference into our attributes

2023-03-02 09:33 UTC, Serhiy1 approved these changes

2023-03-02 09:36 UTC, merged