Robin/decode receipt
rkvst/rkvst-receipt-scitt pull request #5
Opened 2023-03-19 12:24 UTC by robinbryce

* Verification of native ethereum EIP 1186 proofs covering all values recorded on chain for an RKVST event
* Recovery of the original RKVST Event API values from the raw blockchain proofs

Some top level elements, notably the event identity, are to follow

2023-03-20 10:35 UTC, Serhiy1 commented on rkvst_receipt_scitt/attribute_decoder.py
> +        value = decode(attrvalue, binary).decode("utf-8")
This can be replaced with

```python
with contextlib.supress(DeserializationError)
    value = decode(attrvalue, binary).decode("utf-8")

```

2023-03-20 10:36 UTC, Serhiy1 commented on rkvst_receipt_scitt/elementmetadata.py
> +    def __init__(self, storageproofs, lenlast=None):
missing type hints

2023-03-20 10:37 UTC, Serhiy1 commented on rkvst_receipt_scitt/elementmetadata.py
> +    def __init__(self, storageproofs, metadata):
missing type hints

2023-03-20 10:37 UTC, Serhiy1 commented on rkvst_receipt_scitt/elementmetadata.py
> +    def __init__(self, storageproofs, metadata):
missing type hints

2023-03-20 12:04 UTC, honourfish approved these changes

2023-03-20 12:04 UTC, honourfish commented on unittests/test_khipureceipt.py
> +        self.assertIn("timestamp_accepted", event)
minor: can we test for these specific values as well?

2023-03-21 20:09 UTC, robinbryce commented on rkvst_receipt_scitt/khipureceipt.py
> +iWHO_ISSUER = 0
i for index ? if that is not obvious I will just remove them

2023-03-21 20:18 UTC, robinbryce commented on rkvst_receipt_scitt/attribute_decoder.py
> +        value = decode(attrvalue, binary).decode("utf-8")
I'm not sure it can, @honourfish has two different paths here depending on whether the exception is caught. suppressing it prevents that from working. The linter confirms this. When I make the suggested change it marks the remainder of the function as dead clode

2023-03-22 08:12 UTC, honourfish commented on rkvst_receipt_scitt/khipureceipt.py
> +iWHO_ISSUER = 0
I find it obvious in context of a loop, not as a global? I think i would prefer they are removed, but would not hold up a PR for it

2023-03-22 08:39 UTC, honourfish approved these changes

2023-03-22 09:28 UTC, eccles requested changes

2023-03-22 09:28 UTC, eccles commented on rkvst_receipt_scitt/elementmetadata.py
> +        raise AttributeError(f"{name} is not a field or an attribute")
ah - belay that - its ok

2023-03-22 09:28 UTC, eccles commented on docs/conf.py
> +    "**.ipynb_checkpoints",
some of these are unnecessary - functests, ipynb, scripts

2023-03-22 09:28 UTC, eccles commented on requirements.txt
> +rfc3339
version?

2023-03-22 09:28 UTC, eccles commented on rkvst_receipt_scitt/elementmetadata.py
> +            start += count
There is an idiomatic way of iterating 2 lists simultaneously usin the zop() function. This is idiomatic and is well-known viz:

`for count,  lenlast  in zip(metadata["slots"], metadata["lenlasts"]):
              self.arrays.append(...)
`

2023-03-22 13:18 UTC, merged